---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: pair
  namespace: pair
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/dester37/pair.git