# Default values for helm. 
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
#nodeSelector: "rpi3"
image:
  repository: "ghcr.io/dester37"
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v1.0.3-f0f8b6d"
  arch: "arm"
  os: "linux"
secrets:
  - name: "pair"
    env: "TELEGRAM_APITOKEN"
    key: "TELEGRAM_APITOKEN"
  - name: "pair"
    env: "OPENAI_API_KEY"
    key: "OPENAI_API_KEY"
MOODE_BASE_URL: "http://192.168.88.9"