name: pAIR-CICD

on: 
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - helm/Chart.yaml

permissions:
  contents: write

jobs:
  ci:
     name: CI
     runs-on: ubuntu-latest
     
     steps:
       - name: Checkout
         uses: actions/checkout@v2
         with:
           fetch-depth: 0 

       - name: Set up QEMU
         uses: docker/setup-qemu-action@v1 

       - name: Run test
         run: make test

       - name: Log in to GitHub registry
         run: echo "${{ secrets.pAIR_GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

#       - name: Login to Docker Hub
#         uses: docker/login-action@v1
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}

       - name: Build and Push
         uses: actions/checkout@v2
         with:
           fetch-depth: 0
       - run: echo "VERSION=$(git describe --tags --abbrev=0)-$(git rev-parse --short HEAD)" >> $GITHUB_ENV
       - run: docker build -t ${REGISTRY}/${APP}:${VERSION}-${TARGETOS}-${TARGETARCH} .   
         env:
           APP: pair
           TARGETOS: linux
           TARGETARCH: arm
           REGISTRY: ${{ secrets.pAIR_GITHUB_USERNAME }}
       - run: docker push ${REGISTRY}/${APP}:${VERSION}-${TARGETOS}-${TARGETARCH}
         env:
           APP: pair
           TARGETOS: linux
           TARGETARCH: arm
           REGISTRY: ${{ secrets.pAIR_GITHUB_USERNAME }}

  cd:
     name: CD
     needs: ci
     runs-on: ubuntu-latest
          
     steps:

     - uses: actions/checkout@v2
       with:
         fetch-depth: 0
     - run: echo "VERSION=$(git describe --tags --abbrev=0)-$(git rev-parse --short HEAD)" >> $GITHUB_ENV

     - uses: mikefarah/yq@master
       with:
         cmd: yq -i '.image.tag=strenv(VERSION)' helm/values.yaml

     - run: |
         git config user.name github-actions
         git config user.email github-actions@github.com
         git commit -am "update version $VERSION"
         git push
